import localFont from "next/font/local";
import "./globals.css";
import Header from "@/partials/Header";
import Footer from "@/partials/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "CTU Client",
  description: "Generated by create next app",
  icons: {
    icon: 'https://www.ctu.edu.vn/images/upload/logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />

        
        {children}
        <Footer />
      </body>
    </html>
  );
}
