import localFont from "next/font/local";
import "./globals.css";
import Header from "@/partials/Header";
import Footer from "@/partials/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />

        <div className="h-20 flex justify-center items-center text-2xl text-white" style={{ backgroundColor: '#e3bf00' }}>Đồng thuận - Tận tâm - Chuẩn mực - Sáng tạo</div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
